### ISSUE TITLE
Release 1.7.02

### ISSUE THREAD

**Issue by munderseth** [munderseth/testspace.getting-started#4]
Release on ABC Feature
```
xtestspace:
   branch: main
   specs:
     - path: "manual/hello.md"
```
