### ISSUE TITLE
Release 1.7.02

### ISSUE THREAD

**Issue by munderseth** [munderseth/testspace.getting-started#7]
Focus on new Feature `ABC`
```
testspace:
  branch: "main"
  specs:
    - path: "manual/hello.md"
```
